### ISSUE TITLE
Unable to download attached files from doctype

### ISSUE THREAD

**Issue by nanoharsha** [frappe/mobile#84]
We have tried downloading attached files from attached doctypes and are unable to download the files. In android it says download failed, in ios there is no action at all

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/61 and uploaded on app stores

**Comment by nanoharsha** [comment]
That was super quick 👏🏽👏🏽👍🏽

**Comment by nanoharsha** [comment]
I am still unable to download a file from IOS app after updating the app. Pls find video of the same
https://user-images.githubusercontent.com/10630319/133872962-113feec5-99b8-43e3-88f1-a9120058c51e.MOV

**Comment by nanoharsha** [comment]
I checked on android and its working fine, unable to still access it on IOS
