### ISSUE TITLE
Posting time showing big gray field

### ISSUE THREAD

**Issue by Helkyd** [frappe/mobile#88]
When doing an invoice after selecting the company the posting time field is shown as a big gray field

![Screenshot_20210917-104926](https://user-images.githubusercontent.com/20396898/133763478-318cf0bb-24fb-4e34-905d-633643f56201.png)

**Comment by sumitbhanushali** [comment]
this is fixed in latest update, please check for update on play store

**Comment by Helkyd** [comment]
I have updated and still the same issue!

How to check which version of the app I have?

**Comment by sumitbhanushali** [comment]
![Screenshot_20210917-172135__01.jpg](https://user-images.githubusercontent.com/9103781/133778332-1664518d-6ef0-4675-b6a6-0a206fa597e5.jpg)

I have pushed new update, you should receive it soon

**Comment by sumitbhanushali** [comment]
fixed in https://github.com/frappe/mobile/pull/86

**Comment by Helkyd** [comment]
Hi,
If you have fixed until now the problem exists... I have uninstalled and installed again and the issue is still here as you can see
![Uploading Screenshot_20210917-210957.png…]()

**Comment by sumitbhanushali** [comment]
deployed fix on v1.1
